### ISSUE TITLE
Dataset AFAM corso mancante

### ISSUE THREAD

**Issue by denismarini** [MIPA-CINECA/codifiche-mur#1]
Salve,

Riporto la seguente Issue che è stata aperta nel repository dell'avviso 1.3.1 UNIAFAM 

Buon giorno,
abbiamo notato che manca il corso
SCUOLA DI ARMONICA A BOCCA CROMATICA- DCPL 73

in generale vorremmo chiedere, qualora una Istituzione attivi un nuovo corso, a chi dovrebbe rivolgersi per far aggiornare il dataset relativo.

**Comment by andreafronda** [comment]
salve, abbiamo aggiunto la classe DCPL 73 al file delle classi, dove mancava  https://github.com/MIPA-CINECA/codifiche-mur/blob/main/AFAM/classi.csv

**Comment by denismarini** [comment]
Grazie @andreafronda!
