### ISSUE TITLE
Master di primo e secondo livello

### ISSUE THREAD

**Issue by isidata23** [MIPA-CINECA/codifiche-mur#3]
Gentilissimi buongiorno

Nel dataset corsi dell'AFAM, mancano i codici dei corsi Master di primo e secondo livello.

Grazie per l'attenzione riservataci, ISIDATA

**Comment by denismarini** [comment]
Ciao @andreafronda,

In qualche modo si riesce ad avere i codici dei Master per gli AFAM come richiesto?

**Comment by andreafronda** [comment]
@denismarini sentito l'ufficio di sstatistica del MUR, i corsi Master al momento non sono presenti nell’elenco del file corsi.csv della sezione AFAM. Appena sarà convalidata l’offerta formativa si provvederà a pubblicare l’aggiornamento.
