### ISSUE TITLE
DAPL08 doppione

### ISSUE THREAD

**Issue by isidata23** [MIPA-CINECA/codifiche-mur#4]
Buongiorno
vorrei portare alla vostra attenzione la presenza del doppione DAPL08 all'interno della lista
https://github.com/MIPA-CINECA/codifiche-mur/blob/main/AFAM/classi.csv

La voce PROGETTAZIONE ARTISTICA PER L'IMPRESA poi comunque è già presente per DAPL06;PROGETTAZIONE ARTISTICA PER L'IMPRESA;PL

Grazie

Fabio Fonzo, ISIDATA Srl

**Comment by denismarini** [comment]
Ciao @andreafronda,
Quando potete intervenire su questa issue?

**Comment by andreafronda** [comment]
Il problema segnalato non è più presente
