### ISSUE TITLE
IFS03 - Dubbio interazione con IFS07 per corsi di studio vecchio ordinamento

### ISSUE THREAD

**Issue by AlessandroGualdaniUniGe** [MIPA-CINECA/codifiche-mur#5]
Buonasera,
in merito alla misura 1.3.1 https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam ho un dubbio (issue: https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/issues/196 ) su scenari tipo il seguente:

1. lo studente X ha una variazione su una laurea del vecchio ordinamento
2. viene invocata la IFS07.1 con academic_system=old e e sync_mode=full, quindi viene restituito (assieme a quello di altri studenti) l'hash dello studente X
3. ANIS invoca la IFS03.1 con il codice fiscale (tax_code) dello studente X; tuttavia, la specifica OpenAPI https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/main/src/IFS03-titoli.yaml prevede che nella response l'attributo degree_course_code sia obbligatorio, quindi come facciamo a restituire il dettaglio di un titolo di studio del vecchio ordinamento dal momento che i corsi di laurea del vecchio ordinamento non hanno degree_course_code?

Il dubbio può essere generalizzato ovvero come dobbiamo trattare i corsi di laurea/titoli (sia IFS02 che IFS03) nel caso del vecchio ordinamento, che non prevedono un degree_course_code, in base al repository del MUR https://github.com/MIPA-CINECA/codifiche-mur/tree/main ?
Non dobbiamo selezionare iscrizioni/titoli del vecchio ordinamento in nessuna estrazione? Però in tal caso verrebbe un po' meno l'utilità del filtro academic_system=old della IFS07.1.

Ad oggi, nel repository Università https://github.com/MIPA-CINECA/codifiche-mur/blob/main/Universita/csv/corsi.csv mi sembra che, per l'Università degli Studi di Genova (INSTITUTE_CODE: 11) ci siano solo i degree_course_code dal 2001 in poi (corsi di studio D.M. 509/1999 e successivi) ma non quelli vecchio ordinamento (per cui effettivamente non esiste un degree_course_code inteso come chiave anagrafe).

Teoricamente, per il vecchio ordinamento, si potrebbe valorizzare il campo degree_course_code con il codice univoco USTAT utilizzato dall'Ufficio di Statistica (similmente a come viene fatto per l'invio dei dati all'Anagrafe Nazionale Studenti ANS) anche se il significato non è proprio lo stesso dal momento che il codice univoco USTAT non è storicizzato per coorte mentre la chiave anagrafe dei corsi di studio D.M. 509 e D.M. 270/2004 è storicizzata per coorte (oltre ad essere più "dettagliata", riferendosi ad una specifica sede, curriculum, classe di laurea).

Saluti.

Gualdani Alessandro

**Comment by andreafronda** [comment]
sentito l'ufficio di statica del MUR, confermiamo che ANIS non include i corsi del vecchio ordinamento
