### ISSUE TITLE
Dataset discipline

### ISSUE THREAD

**Issue by ldonnola** [MIPA-CINECA/codifiche-mur#7]
Buongiorno, 
in IFS01 si fa riferimento a "learning_sad", "learning_name", "learning_code". Dove possiamo reperire tali campi?

**Comment by denismarini** [comment]
Buongiorno @ldonnola,

Queste sono informazioni in possesso dell'istituto e non codificate in questo Repository.

Spero di essere stato utile

**Comment by ldonnola** [comment]
Buongiorno @denismarini 
grazie della risposta intanto, quindi il learnig_code quindi fa riferimento al codice interno?

**Comment by denismarini** [comment]
Buongiorno @ldonnola,

Confermo!
